version: '3.8'

services:
  postgres:
    container_name: Aiko_postgres
    image: postgres:10.5
    restart: always
    ports:
      - :${POSTGRES_PORT}:5432
    networks:
      - aiko_network
    volumes: 
      - ./postgres:/var/lib/postgresql/data
      - ./file.sql:/docker-entrypoint-initdb.d/file.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "Aiko"
  api:
    container_name: Aiko_api
    build: ./api
    restart: always
    ports:
      - 3000:3000
    networks:
      - aiko_network
    working_dir: /api
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "Aiko"
      HOST: ${HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres
    command: "node server.js"
  nodejs:
    container_name: Aiko
    build: ./app
    restart: always
    ports:
      - 3001:3000
    networks:
      - aiko_network
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "Aiko"
      HOST: ${HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - api
    command: "npm start"

volumes:
  postgres:
    driver: local

networks:
  aiko_network:
    name: aiko_network