version: '3.8'

services:
  postgres:
    container_name: Aiko_postgres
    image: postgres:10.5
    restart: always
    ports:
      - :${POSTGRES_PORT}:5432
    networks:
      - aiko_network
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "Aiko"

  nodejs:
    container_name: Aiko
    build: ./app
    restart: always
    networks:
      - aiko_network
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "Aiko"
    depends_on:
      - postgres
    command: "npm start"

networks:
  aiko_network:
    name: aiko_network